name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./FunctionalExtensions/FunctionalExtensions.sln
    - name: Build release
      run: dotnet build ./FunctionalExtensions/FunctionalExtensions.sln --configuration Release --no-restore
    - name: Deploy Base
      uses: actions/upload-artifact@v2
      with:
        name: FunctionalExtensions.Base
        path: /home/runner/work/FunctionalExtensions/FunctionalExtensions/FunctionalExtensions/FunctionalExtensions.Base/bin/Release/net5.0/FunctionalExtensions.Base.dll
    - name: Deploy GenericProvider
      uses: actions/upload-artifact@v2
      with:
        name: FunctionalExtensions.GenericProvider
        path: /home/runner/work/FunctionalExtensions/FunctionalExtensions/FunctionalExtensions/FunctionalExtensions.GenericProvider/bin/Release/net5.0/FunctionalExtensions.GenericProvider.dll
