name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: we are here
      run: pwd
    - name: list some key files
      run: ls -lrt
    - name: Restore dependencies
      run: dotnet restore ./FucntionalExtensions/FunctionalExtensions.sln
    - name: Build
      run: dotnet build ./FucntionalExtensions/FunctionalExtensions.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./FucntionalExtensions/FunctionalExtensions.sln --no-build --no-restore --verbosity normal
