name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: we are here
      run: pwd
    - name: enter folder
      run: cd FunctionalExtensions
    - name: we are here
      run: pwd
    - name: list files
      run: ls -al
    - name: Restore dependencies
      run: dotnet restore /home/runner/work/FunctionalExtensions/FucntionalExtensions/FucntionalExtensions/FunctionalExtensions.sln
    - name: Build
      run: dotnet build /home/runner/work/FunctionalExtensions/FucntionalExtensions/FucntionalExtensions/FunctionalExtensions.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test /home/runner/work/FunctionalExtensions/FucntionalExtensions/FucntionalExtensions/FunctionalExtensions.sln --no-build --no-restore --verbosity normal
