name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./FunctionalExtensions/FunctionalExtensions.sln
    - name: Build
      run: dotnet build ./FunctionalExtensions/FunctionalExtensions.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./FunctionalExtensions/FunctionalExtensions.sln --no-restore --verbosity normal
