name: Publish Nugets  

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./FunctionalExtensions/FunctionalExtensions.sln
    - name: Build release
      run: dotnet build ./FunctionalExtensions/FunctionalExtensions.sln --configuration Release --no-restore
    - name: Publish Base Nuget
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
        PROJECT_FILE_PATH: ./FunctionalExtensions/FunctionalExtensions.Base/FunctionalExtensions.Base.csproj  
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish GenericProvider Nuget
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
        PROJECT_FILE_PATH: ./FunctionalExtensions/FunctionalExtensions.GenericProvider/FunctionalExtensions.GenericProvider.csproj  
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
